version = 0.1
[default.deploy.parameters]
stack_name = "lamda-tf"
resolve_s3 = true
s3_prefix = "lamda-tf"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "DomainName=api.yp3yp3.online",
    "CertificateArn=arn:aws:acm:us-east-1:992382507075:certificate/4c818c22-adc8-458b-a2bd-9a41be8ef182",
    "GitHubRepoName=yp3yp3/api-rds-provisioning"
]
